const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

// ensure uploads/reports folder exists
function ensureDirExists(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function addSectionTitle(doc, text) {
  doc.moveDown(1);
  doc.fontSize(14).font("Helvetica-Bold").text(text);
  doc.moveDown(0.3);
  doc
    .moveTo(doc.x, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(0.5);
}

function formatDate(d) {
  if (!d) return "-";
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

/**
 * Training Summary ke liye PDF generate karta hai
 * @param {Object} reportDoc - Report mongoose document
 * @param {Object} reportData - dataFetchService.fetchReportData ka raw output
 * @returns {Promise<string>} pdf file path
 */
async function generateTrainingSummaryPDF(reportDoc, reportData) {
  return new Promise((resolve, reject) => {
    try {
      const reportsDir = path.join(__dirname, "..", "uploads", "reports");
      ensureDirExists(reportsDir);

      const fileName = `report_${reportDoc._id}.pdf`;
      const filePath = path.join(reportsDir, fileName);

      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // ================== HEADER ==================
      doc
        .fontSize(18)
        .font("Helvetica-Bold")
        .text("Saksham – NDMA Training Summary Report", {
          align: "center",
        });

      doc.moveDown(0.5);
      doc.fontSize(11).font("Helvetica").text(`Report Title: ${reportDoc.title}`, {
        align: "center",
      });

      doc
        .fontSize(10)
        .text(`Generated On: ${new Date().toLocaleString("en-IN")}`, {
          align: "center",
        });

      doc.moveDown(1);
      doc
        .fontSize(9)
        .font("Helvetica")
        .text(
          `Generated By: ${reportDoc.generated_by_role?.toUpperCase() || "ADMIN"}`,
          { align: "center" }
        );

      doc.moveDown(1.5);

      // ================== SUMMARY SECTION ==================
      const summary = reportData.summary || {};

      const totalTrainings =
        summary.total_trainings ?? summary.totalTrainings ?? 0;
      const totalParticipants =
        summary.total_participants ?? summary.totalParticipants ?? 0;
      const uniqueDistricts =
        summary.unique_districts ?? summary.uniqueDistricts ?? 0;
      const avgParticipants =
        summary.avg_participants_per_training ??
        summary.avgParticipants ??
        0;
      const dateRangeCovered =
        summary.date_range_covered ?? summary.dateRangeCovered ?? "No data";

      addSectionTitle(doc, "1. Key Summary");

      doc.fontSize(11).font("Helvetica");
      doc.text(`• Total Trainings Conducted: ${totalTrainings}`);
      doc.text(`• Total Participants (Claimed): ${totalParticipants}`);
      doc.text(`• Unique Districts Covered: ${uniqueDistricts}`);
      doc.text(`• Average Participants per Training: ${avgParticipants}`);
      doc.text(`• Data Coverage: ${dateRangeCovered}`);

      // ================== THEME DISTRIBUTION ==================
      const themes =
        reportData.theme_distribution || reportData.themeDistribution || [];

      if (themes.length) {
        addSectionTitle(doc, "2. Trainings by Theme");

        doc.fontSize(11).font("Helvetica-Bold");
        doc.text("Theme", { continued: true, width: 200 });
        doc.text("Sessions", { continued: true, width: 80 });
        doc.text("Participants", { continued: true, width: 100 });
        doc.text("Share (%)", { width: 60 });
        doc.moveDown(0.3);
        doc.font("Helvetica");
        doc
          .moveTo(doc.x, doc.y)
          .lineTo(doc.page.width - doc.page.margins.right, doc.y)
          .stroke();
        doc.moveDown(0.3);

        themes.forEach((item) => {
          if (doc.y > doc.page.height - 80) {
            doc.addPage();
          }

          doc.text(item.theme || "N/A", { continued: true, width: 200 });
          doc.text(String(item.count ?? 0), { continued: true, width: 80 });
          doc.text(String(item.participants ?? 0), {
            continued: true,
            width: 100,
          });
          doc.text(String(item.percentage ?? 0), { width: 60 });
        });
      }

      // ================== DISTRICT BREAKDOWN ==================
      const geo =
        reportData.geographic_breakdown || reportData.districtBreakdown || [];

      if (geo.length) {
        if (doc.y > doc.page.height - 150) {
          doc.addPage();
        }

        addSectionTitle(doc, "3. District-wise Coverage (Top Districts)");

        doc.fontSize(11).font("Helvetica-Bold");
        doc.text("State", { continued: true, width: 120 });
        doc.text("District", { continued: true, width: 140 });
        doc.text("Sessions", { continued: true, width: 80 });
        doc.text("Participants", { width: 100 });
        doc.moveDown(0.3);
        doc.font("Helvetica");
        doc
          .moveTo(doc.x, doc.y)
          .lineTo(doc.page.width - doc.page.margins.right, doc.y)
          .stroke();
        doc.moveDown(0.3);

        geo.slice(0, 25).forEach((d) => {
          if (doc.y > doc.page.height - 80) {
            doc.addPage();
          }

          const state = d.state;
          const district = d.district;
          const trainingCount =
            d.training_count ?? d.trainingCount ?? 0;
          const participantCount =
            d.participant_count ?? d.participantCount ?? 0;

          doc.text(state || "N/A", { continued: true, width: 120 });
          doc.text(district || "N/A", { continued: true, width: 140 });
          doc.text(String(trainingCount), {
            continued: true,
            width: 80,
          });
          doc.text(String(participantCount), { width: 100 });
        });
      }

      // ================== MONTHLY TRENDS (Optional) ==================
      const monthly = reportData.monthly_trends || reportData.monthlyTrends || [];

      if (monthly.length) {
        if (doc.y > doc.page.height - 150) {
          doc.addPage();
        }

        addSectionTitle(doc, "4. Monthly Training Trends");

        doc.fontSize(11).font("Helvetica-Bold");
        doc.text("Month", { continued: true, width: 120 });
        doc.text("Trainings", { continued: true, width: 100 });
        doc.text("Participants", { width: 120 });
        doc.moveDown(0.3);
        doc.font("Helvetica");
        doc
          .moveTo(doc.x, doc.y)
          .lineTo(doc.page.width - doc.page.margins.right, doc.y)
          .stroke();
        doc.moveDown(0.3);

        monthly.forEach((m) => {
          if (doc.y > doc.page.height - 80) {
            doc.addPage();
          }

          doc.text(m.month || "-", { continued: true, width: 120 });
          doc.text(String(m.training_count ?? m.trainingCount ?? 0), {
            continued: true,
            width: 100,
          });
          doc.text(String(m.participant_count ?? m.participantCount ?? 0), {
            width: 120,
          });
        });
      }

      // ================== GAP ANALYSIS (Optional) ==================
      const gaps = reportData.gaps || {};
      const zeroDist = gaps.districts_with_zero_trainings || [];
      const inactive = gaps.inactive_districts || [];

      if (zeroDist.length || inactive.length) {
        if (doc.y > doc.page.height - 150) {
          doc.addPage();
        }

        addSectionTitle(doc, "5. Coverage Gaps (High Priority)");

        doc.fontSize(11).font("Helvetica-Bold").text("Districts with Zero Trainings:");
        doc.moveDown(0.3);
        doc.font("Helvetica");
        if (!zeroDist.length) {
          doc.text("• None (All districts have some training coverage)");
        } else {
          zeroDist.slice(0, 15).forEach((d) => {
            doc.text(`• ${d.name}, ${d.state}`);
          });
        }

        doc.moveDown(0.8);
        doc.fontSize(11).font("Helvetica-Bold").text("Inactive Districts (No Training in 6+ Months):");
        doc.moveDown(0.3);
        doc.font("Helvetica");
        if (!inactive.length) {
          doc.text("• None (No long-term inactivity detected)");
        } else {
          inactive.slice(0, 15).forEach((d) => {
            doc.text(
              `• ${d.name}, ${d.state} – Last training: ${formatDate(
                d.last_training_date
              )} (${d.days_since_last} days ago)`
            );
          });
        }
      }

      // ================== FOOTER ==================
      doc.moveDown(2);
      doc.fontSize(9).font("Helvetica-Oblique");
      doc.text(
        "This report is auto-generated by the Saksham NDMA Training Monitoring System.",
        {
          align: "center",
        }
      );

      doc.end();

      stream.on("finish", () => resolve(filePath));
      stream.on("error", (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  generateTrainingSummaryPDF,
};
