const TrainingSession = require("../models/TrainingSession.js");
const District = require("../models/District.js");
const Report = require("../models/Report");


const isOwnerOrAdmin = async (req, res, next) => {
    try {
      const { id } = req.params;
      const userRole = req.user.role;
      const userId = req.user.id;
      
      console.log('isOwner check:', { id, userRole, userId });
      
      // Find the training
      const training = await TrainingSession.findById(id);
      
      if (!training) {
        const error = new Error('Training session not found');
        error.status = 404;
        throw error;
      }
      
      // NDMA Full access to everything
      if (userRole === 'ndma_admin') {
        console.log('Access: NDMA Admin - FULL ACCESS');
        req.training = training; // Attach training to request
        return next();
      }
      
      // SDMA - Access to trainings in their state
      if (userRole === 'sdma_admin') {
        const district = await District.findById(training.district_id);
        const userState = req.user.state;
        
        if (district && userState && 
            district.state.toLowerCase() === userState.toLowerCase()) {
          console.log('Access: SDMA Admin - SAME STATE');
          req.training = training;
          return next();
        } else {
          const error = new Error('Access denied. You can only access trainings in your state');
          error.status = 403;
          throw error;
        }
      }
      
      // Trainer - Must be the owner
      if (userRole === 'trainer') {
        // Get MongoDB user ID from req.user (set by requireAuth middleware)
        const mongoUserId = req.user.id;

        if (!mongoUserId) {
          const error = new Error('User ID not found. Please ensure user is properly authenticated.');
          error.status = 400;
          throw error;
        }
        
        // Compare MongoDB ObjectIds (both are MongoDB ObjectIds now)
        if (training.trainer_id.toString() === mongoUserId.toString()) {
          console.log('Access: Trainer - IS OWNER');
          req.training = training;
          return next();
        } else {
          const error = new Error('Access denied. You can only access your own training sessions');
          error.status = 403;
          throw error;
        }
      }
      
      const error = new Error('Access denied. Insufficient permissions');
      error.status = 403;
      throw error;
      
    } catch (error) {
      next(error);
    }
  };


const isReportOwnerOrNdma = async (req, res, next) => {
  try {
    const { id } = req.params;
    const userRole = req.user.role;
    const userId = req.user.id || req.user._id;

    console.log("isReportOwnerOrNdma check:", { id, userRole, userId });

    // 1) Report find karo
    const report = await Report.findById(id);

    if (!report) {
      const error = new Error("Report not found");
      error.status = 404;
      throw error;
    }

    // 2) NDMA = FULL ACCESS (koi bhi report dekh/ download sakta hai)
    if (userRole === "ndma_admin") {
      console.log("Access: NDMA Admin - FULL ACCESS to report");
      req.report = report; // controller ko ready object de diya
      return next();
    }

    // 3) SDMA = sirf apne banaye hue reports
    if (userRole === "sdma_admin") {
      if (String(report.generated_by) === String(userId)) {
        console.log("Access: SDMA Admin - OWN REPORT");
        req.report = report;
        return next();
      } else {
        const error = new Error(
          "Access denied. You can only access reports generated by you"
        );
        error.status = 403;
        throw error;
      }
    }

    // 4) Baaki roles allowed hi nahi (waise routes me role filter already laga hoga)
    const error = new Error("Access denied. Insufficient permissions for reports");
    error.status = 403;
    throw error;
  } catch (error) {
    next(error);
  }
};

module.exports = {isOwnerOrAdmin, isReportOwnerOrNdma};